Fix init script.

diff --git a/debian/aspsms-t.init b/debian/aspsms-t.init
--- a/debian/aspsms-t.init
+++ b/debian/aspsms-t.init
@@ -18,12 +18,20 @@ DESC="aspsms jabber transport"
 NAME=aspsms-t
 STARTDIR=/usr/bin
 DAEMON=$STARTDIR/$NAME
-DAEMON_ARGS="-c /etc/aspsms-t.xml"
+CONF="/etc/aspsms/aspsms-t.xml"
+DAEMON_ARGS="-c $CONF"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
+
+# Exit if the package is not installed
+if [ ! -r "$CONF" ];
+then
+  echo "Please configure $CONF before you can start aspsms-t!"
+  exit 0
+fi
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
@@ -41,35 +49,43 @@ VERBOSE=1
 #
 do_start()
 {
-        RESULT=2
-        if [ -f "$PIDFILE" ]; then
-                RUNNING=$(ps faux | grep "$(cat $PIDFILE)" | grep -v grep)
-                echo
-                if [ -z "$RUNNING" ]; then
-                        echo "$PIDFILE does already exist, but $NAME does not seem to run already. i'm going to delete $PIDFILE and will proceed with the startup sequence." 
-                else
-                        echo "$PIDFILE does already exist. $NAME seems to be running already."
-                        exit 1
-                fi
+  RESULT=2
+  if [ -f "$PIDFILE" ]; 
+  then
+    RUNNING=$(ps faux | grep "$(cat $PIDFILE)" | grep -v grep)
+    echo
+    if [ -z "$RUNNING" ];
+    then
+      echo "$PIDFILE does already exist, but $NAME does not seem to run 
+already. i'm going to delete $PIDFILE and will proceed with the startup 
+sequence." 
+    else
+      echo "$PIDFILE does already exist. $NAME seems to be running already."
+      exit 1
+    fi
 
-        fi
+  fi
 
-        # don't do it using start-stop-daemon. it does not seem to work properly :(
-        su - aspsms -s /bin/bash -c "cd $STARTDIR && $DAEMON $DAEMON_ARGS > /dev/null" & 2>&1 > /dev/null
-        [ "$?" -eq "0" ] && RESULT=0 || echo "couldn't start $NAME"
-        if [ "$RESULT" -eq "0" ]; then
-                # aspsms needs some time to start
-                sleep 1
-                # get pid 
-                PID=$(ps faux | grep "perl.*aspsms-t.pl" | grep -v grep | awk '{print $2}')
-                if [ -z "$PID" ]; then
-                        echo "No process for $NAME found. It does not seem to me that $NAME has been started successfully"
-                        RESULT=2
-                else
-                        echo $PID > $PIDFILE
-                fi
-        fi
-        return $RESULT
+# don't do it using start-stop-daemon. it does not seem to work properly :(
+exec su - aspsms -c "cd $STARTDIR && $DAEMON $DAEMON_ARGS " 2>&1 > /dev/null &
+
+[ "$?" -eq "0" ] && RESULT=0 || echo "couldn't start $NAME"
+if [ "$RESULT" -eq "0" ];
+then
+  # aspsms needs some time to start
+  sleep 1
+  # get pid 
+  PID=$(ps faux | grep "/usr/bin/perl $DAEMON $DAEMON_ARGS" | grep -v grep | awk '{print $2}')
+  if [ -z "$PID" ];
+  then
+    echo "No process for $NAME found. It does not seem to me that $NAME has 
+been started successfully"
+    RESULT=2
+  else
+    echo $PID > $PIDFILE
+  fi
+fi
+return $RESULT
 }
 
 #
@@ -77,38 +93,25 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
-}
-
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+# Return
+#   0 if daemon has been stopped
+#   1 if daemon was already stopped
+#   2 if daemon could not be stopped
+#   other if a failure occurred
+start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+RETVAL="$?"
+[ "$RETVAL" = 2 ] && return 2
+# Wait for children to finish too if this is a daemon that forks
+# and if the daemon is only ever run from this initscript.
+# If the above conditions are not satisfied then add some other code
+# that waits for the process to drop all resources that could be
+# needed by services started subsequently.  A last resort is to
+# sleep for some time.
+start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+[ "$?" = 2 ] && return 2
+# Many daemons don't delete their pidfiles when they exit.
+rm -f $PIDFILE
+return "$RETVAL"
 }
 
 case "$1" in
@@ -128,15 +131,6 @@ case "$1" in
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
   restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
@@ -160,7 +154,6 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
 	exit 3
 	;;
